name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - development
  pull_request:
    paths:
      - "backend/**"

jobs:
  build-test-deploy:
    name: Build, Test & Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Instalar dependências
        working-directory: backend
        run: npm install

      - name: Rodar ESLint
        working-directory: backend
        run: npm run lint

      - name: Compilando TypeScript
        working-directory: backend
        run: tsc

      - name: Gerando documentação com TSOA
        working-directory: backend
        run: npm run doc:generate
